# Generated by Django 4.2.23 on 2025-10-13 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Students',
        ),
    ]
