# Generated by Django 4.2.23 on 2025-10-14 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_rename_user_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('question_1', models.CharField(blank=True, max_length=300)),
                ('question_1_link', models.URLField(blank=True)),
                ('question_2', models.CharField(blank=True, max_length=300)),
                ('question_2_link', models.URLField(blank=True)),
                ('question_3', models.CharField(blank=True, max_length=300)),
                ('question_3_link', models.URLField(blank=True)),
            ],
        ),
    ]
