# Generated by Django 4.2.23 on 2025-10-14 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_contest'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_logged_in', models.BooleanField(default=False)),
                ('leetcode_username', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
