# Generated by Django 4.2.23 on 2025-10-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_islogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_name', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('marks', models.IntegerField(default=0)),
                ('question1_time', models.DurationField(blank=True, null=True)),
                ('question2_time', models.DurationField(blank=True, null=True)),
                ('question3_time', models.DurationField(blank=True, null=True)),
                ('contest_date', models.DateField()),
            ],
        ),
    ]
