# Generated by Django 4.2.23 on 2025-10-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_contestleaderboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestleaderboard',
            name='question1_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contestleaderboard',
            name='question2_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contestleaderboard',
            name='question3_time',
            field=models.BooleanField(default=False),
        ),
    ]
