# Generated by Django 4.2.23 on 2025-10-30 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_contestleaderboard_question1_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contestleaderboard',
            old_name='question1_time',
            new_name='question1',
        ),
        migrations.RenameField(
            model_name='contestleaderboard',
            old_name='question2_time',
            new_name='question2',
        ),
        migrations.RenameField(
            model_name='contestleaderboard',
            old_name='question3_time',
            new_name='question3',
        ),
    ]
